<?php
/*
 * FlowrouteNumbersAndMessagingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace FlowrouteNumbersAndMessagingLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class E911Record implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @var \FlowrouteNumbersAndMessagingLib\Models\E911Attributes|null $attributes public property
     */
    public $attributes = Models\E911Attributes;

    /**
     * @todo Write general description for this property
     * @var string|null $id public property
     */
    public $id;

    /**
     * @todo Write general description for this property
     * @var string|null $type public property
     */
    public $type;

    /**
     * Constructor to set initial or default values of member properties
     */
    public function __construct()
    {
        switch (func_num_args()) {
            default:
                $this->type = 'e911';
                break;
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['attributes'] = $this->attributes;
        $json['id']         = $this->id;
        $json['type']       = $this->type;

        return $json;
    }
}
