<?php
/*
 * FlowrouteNumbersAndMessagingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace FlowrouteNumbersAndMessagingLib\Models;

use JsonSerializable;
use FlowrouteNumbersAndMessagingLib\Utils\DateTimeHelper;

/**
 * @todo Write general description for this model
 */
class Attributes implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @maps address_type
     * @var string|null $address_type public property
     */
    public $address_type;

    /**
     * @todo Write general description for this property
     * @maps $address_type_number
     * @var string|null $address_type_number public property
     */
    public $address_type_number;

    /**
     * @todo Write general description for this property
     * @var string|null $city public property
     */
    public $city;

    /**
     * @todo Write general description for this property
     * @maps country
     * @var 2 character country code
     */
    public $country;

    /**
     * @todo Write general description for this property
     * @var string|null $first_name public property
     */
    public $first_name;

    /**
     * @todo Write general description for this property
     * @var string|null $last_name public property
     */
    public $last_name;

    /**
     * @todo Write general description for this property
     * @maps label
     * @var string|null $label public property
     */
    public $label;

    /**
     * @todo Write general description for this property
     * @maps state
     * @var string|null $state public property
     */
    public $state;

    /**
     * @todo Write general description for this property
     * @maps street_name
     * @var string|null $street_name public property
     */
    public $street_name;

    /**
     * @todo Write general description for this property
     * @var string|null $street_number public property
     */
    public $street_number;

    /**
     * @todo Write general description for this property
     * @var string|null $zipcode public property
     */
    public $zipcode;

    /**
     * Constructor to set initial or default values of member properties
     */
    public function __construct()
    {
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['address_type']        = $this->address_type;
        $json['address_type_number'] = $this->address_type_number;
        $json['city']                = $this->city;
        $json['country']             = $this->country;
        $json['first_name']          = $this->first_name;
        $json['last_name']           = $this->last_name;
        $json['label']               = $this->label;
        $json['street_name']         = $this->street_name;
        $json['street_number']       = $this->street_number;
        $json['zipcode']             = $this->zipcode;

        return $json;
    }
}
