<?php
/*
 * FlowrouteNumbersAndMessagingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace FlowrouteNumbersAndMessagingLib\Models;

/**
 * @todo Write general description for this enumeration
 */
class MessageTypeEnum
{
    /**
     * TODO: Write general description for this element
     */
    const LONGCODE = "longcode";

    /**
     * TODO: Write general description for this element
     */
    const TOLLFREE = "toll-free";
}
