<?php
/*
 * FlowrouteNumbersAndMessagingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace FlowrouteNumbersAndMessagingLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Message implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $from public property
     */
    public $from;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $to public property
     */
    public $to;

    /**
     * @todo Write general description for this property
     * @var string|null $body public property
     */
    public $body;

    /**
     * @todo Write general description for this property
     * @maps media_urls
     * @var array|null $mediaUrls public property
     */
    public $mediaUrls;

    /**
     * @todo Write general description for this property
     * @maps is_mms
     * @var bool|null $isMms public property
     */
    public $isMms;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $from      Initialization value for $this->from
     * @param string $to        Initialization value for $this->to
     * @param string $body      Initialization value for $this->body
     * @param array  $mediaUrls Initialization value for $this->mediaUrls
     * @param bool   $isMms     Initialization value for $this->isMms
     */
    public function __construct()
    {
        if (5 == func_num_args()) {
            $this->from      = func_get_arg(0);
            $this->to        = func_get_arg(1);
            $this->body      = func_get_arg(2);
            $this->mediaUrls = func_get_arg(3);
            $this->isMms     = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['from']       = $this->from;
        $json['to']         = $this->to;
        $json['body']       = $this->body;
        $json['media_urls'] = $this->mediaUrls;
        $json['is_mms']     = $this->isMms;

        return $json;
    }
}
