<?php
/*
 * FlowrouteNumbersAndMessagingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace FlowrouteNumbersAndMessagingLib\Models;

/**
 * @todo Write general description for this enumeration
 */
class RouteTypeEnum
{
    /**
     * TODO: Write general description for this element
     */
    const SIPREG = "sip-reg";

    /**
     * TODO: Write general description for this element
     */
    const HOST = "host";

    /**
     * TODO: Write general description for this element
     */
    const URI = "uri";

    /**
     * TODO: Write general description for this element
     */
    const NUMBER = "number";
}
