<?php
/*
 * FlowrouteNumbersAndMessagingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace FlowrouteNumbersAndMessagingLib;

/**
 * All configuration including auth info and base URI for the API access
 * are configured in this class.
 */
class Configuration
{
    /**
     * The base Uri for API calls
     * @var string
     */

    public static $BASEURI = 'https://api.flowroute.com';

    /**
     * Your Flowroute Tech-Prefix which serves as your username
     * @var string
     */
    public static $basicAuthUserName = 'Your Tech Prefix Here';

    /**
     * Your Flowroute API Secret Key which serves as your password
     * @var string
     */
    public static $basicAuthPassword = 'Your API Secret Key Here';
}
